production:
  adapter:  mysql2
  database: <%= ENV['OPENSHIFT_APP_NAME'] %>
  host:     <%= ENV['OPENSHIFT_MYSQL_DB_HOST'] %>
  username: <%= ENV['OPENSHIFT_MYSQL_DB_USERNAME'] %>
  password: <%= ENV['OPENSHIFT_MYSQL_DB_PASSWORD'] %>
  encoding: utf8

development:
  adapter: sqlite3
  database: db/test.sqlite3
