production:
  adapter:  <%= ENV['REDMINE_DB_ADAPTER'] %>
  database: <%= ENV['REDMINE_DB_BASE'] %>
  host:     <%= ENV['REDMINE_DB_HOST'] %>
  username: <%= ENV['REDMINE_DB_USER'] %>
  password: <%= ENV['REDMINE_DB_PASS'] %>
  encoding: utf8

development:
  adapter: sqlite3
  database: db/test.sqlite3
